export const robots=[{
    name:"Farhan",
    id:"1",
    email:"fk912254@gmail.com"
},{
    name:"Falak",
    id:"2",
    email:"MereBaigan@gmail.com"
},{
    name:"Saif",
    id:"3",
    email:"OverProtectiveActor@gmail.com"
},{
    name:"Daniyal",
    id:"4",
    email:"DannuPaaji@gmail.com"
},{
    name:"Fareha",
    id:"5",
    email:"AmmaJi@gmail.com"
},{
    name:"RaziaParween",
    id:"6",
    email:"ParweenAunty@gmail.com"
},{
    name:"Nashat Ahmad",
    id:"7",
    email:"Pops@gmail.com"
},{
    name:"Azra",
    id:"8",
    email:"HappuBirthday@gmail.com"
}]